import 'server-only'
import { generateText } from 'ai'
import { getLanguageModel } from '@/lib/ai/vercel-client'
import { buildUnifiedPrompt, type BuildPromptOptions } from '@/lib/prompts/unified/prompt-builder'
import type { SectionContext } from '@/lib/prompts/types'
import { cleanNonCitationArtifacts } from '@/lib/citations/post-processor'
// DEDUPLICATION NOTES:
// - Evidence tracking moved to pipeline.ts (single point of control)
// - Comprehensive quality assessment consolidated in pipeline.ts 
// - Basic quality scoring retained here for individual sections
// - Citation processing streamlined (no double collection)

/**
 * Unified content generator using single skeleton template with contextual data
 * Replaces the multiple hard-coded prompt approach with data-driven generation
 * 
 * ARCHITECTURAL SEPARATION:
 * - This module: Core generation logic, streaming, basic quality scoring
 * - Pipeline module: Orchestration, comprehensive quality review, evidence tracking, overlap detection
 * 
 * Features:
 * - Single template scales from sentence → section → paper  
 * - Coherence through rolling summaries
 * - Sentence-level streaming
 * - Basic quality metrics (comprehensive assessment in pipeline)
 */

export type StreamEvent =
  | { type: 'sentence'; data: { text: string } }
  | { type: 'progress'; data: { stage: string; progress: number; message: string; [key: string]: unknown } }
  | { type: 'error'; data: { message: string } }


export interface UnifiedGenerationConfig {
  context: SectionContext
  options?: BuildPromptOptions
  
  // Stream tracking
  onStreamEvent?: (event: StreamEvent) => void
}

/**
 * Citation entry from structured output
 * index: The [N] marker number in the prose
 * paperId: The paper being cited
 * quote: Optional supporting sentence (derived post-hoc, not generated by LLM)
 */
export interface StructuredCitation {
  index: number
  paperId: string
  quote?: string
}

export interface UnifiedGenerationResult {
  content: string
  /** Raw citations from structured output - one entry per citation occurrence, in order */
  citations: StructuredCitation[]
  tokensUsed: number
  generationTime: number
  qualityScore: number
}

/**
 * Calculate basic quality score (simplified version - full quality assessment done in pipeline)
 */
function calculateBasicQualityScore(params: {
  content: string
  citations: StructuredCitation[]
  targetWords: number
  minCitationsExpected?: number
}): number {
  const { content, citations, targetWords, minCitationsExpected } = params
  
  const wordCount = content.split(' ').length
  const lengthScore = Math.min(100, (wordCount / targetWords) * 100)
  
  // Citation score: scale to expected citations from profile
  // If no expectation provided, use actual citations as the baseline (self-calibrating)
  const citationTarget = minCitationsExpected || Math.max(citations.length, 1)
  const citationScore = Math.min(100, (citations.length / citationTarget) * 100)
  
  // Basic calculation - comprehensive quality assessment handled by pipeline
  return Math.round((lengthScore + citationScore) / 2)
}

// Helper to resolve generation options with defaults
function resolveGenOptions(options: BuildPromptOptions): Required<Pick<BuildPromptOptions, 'temperature' | 'maxTokens'>> & BuildPromptOptions {
  return {
    ...options,
    temperature: options.temperature ?? 0.4,  // Use nullish coalescing for cleaner defaults
    maxTokens: options.maxTokens ?? 8000
  }
}

// Direct prompt building - no caching complexity
async function buildPromptData(
  context: SectionContext, 
  options: BuildPromptOptions
): Promise<{ system: string, user: string }> {
  return await buildUnifiedPrompt(context, options)
}

/**
 * Parse [@paperId] citation markers from generated markdown.
 * Returns StructuredCitation[] with sequential index numbers and the paperId.
 * Also handles [@id1; @id2] multi-cite syntax.
 */
function parseCitationsFromMarkdown(content: string): StructuredCitation[] {
  const citations: StructuredCitation[] = []
  let index = 1

  // Match [@paperId] and [@id1; @id2] patterns
  const markerRegex = /\[@([^\]]+)\]/g
  let match
  while ((match = markerRegex.exec(content)) !== null) {
    const inner = match[1] // e.g. "abc-123" or "abc-123; @def-456"
    // Split on semicolons for multi-cite markers
    const ids = inner.split(/;\s*@?/).map(s => s.replace(/^@/, '').trim()).filter(Boolean)
    for (const paperId of ids) {
      citations.push({ index, paperId })
      index++
    }
  }

  return citations
}

/**
 * Main unified generation function using generateText with inline [@paperId] citations.
 *
 * Architecture: The LLM writes full markdown prose with [@paperId] markers placed
 * inline where citations belong. No JSON schema, no structured output — 100% of the
 * token budget goes to prose. Citations are parsed post-hoc from the text.
 *
 * This follows the P-Cite (post-hoc citation) pattern recommended by NeurIPS 2025
 * research for high-stakes academic writing: generate prose first, verify citations after.
 */
export async function generateWithUnifiedTemplate(
  config: UnifiedGenerationConfig
): Promise<UnifiedGenerationResult> {
  
  const startTime = Date.now()
  const {
    context,
    options = {},
    onStreamEvent
  } = config

  const progress = (stage: string, pct: number, msg: string, data?: Record<string, unknown>) => {
    onStreamEvent?.({ type: 'progress', data: { stage, progress: pct, message: msg, ...data }})
  }

  let fullContent = ''
  let tokensUsed = 0

  progress('context', 10, 'Preparing evidence for this section...')
  
  const promptData = await buildPromptData(context, options)
  
  progress('generation', 20, 'Writing section content...')
  
  const resolvedOptions = resolveGenOptions(options)

  const { text, usage } = await generateText({
    model: getLanguageModel(),
    system: promptData.system,
    prompt: promptData.user,
    temperature: resolvedOptions.temperature,
    maxOutputTokens: resolvedOptions.maxTokens
  })

  fullContent = text
  tokensUsed = usage?.totalTokens || 0

  // Clean any artifacts that shouldn't be in output
  fullContent = cleanNonCitationArtifacts(fullContent)

  // Parse [@paperId] markers from the generated prose
  const collectedCitations = parseCitationsFromMarkdown(fullContent)

  // Emit a single "sentence" event for compatibility with existing streaming hooks
  if (fullContent) {
    onStreamEvent?.({ type: 'sentence', data: { text: fullContent }})
  }
  
  progress('generation', 50, 'Section written successfully', {
    word_count: fullContent.split(' ').length,
    citations: collectedCitations.length
  })
  
  const qualityScore = calculateBasicQualityScore({
    content: fullContent,
    citations: collectedCitations,
    targetWords: options.targetWords || 300,
    minCitationsExpected: Math.max(collectedCitations.length, 1)
  })

  progress('complete', 100, 'Section complete')

  return {
    content: fullContent,
    citations: collectedCitations,
    tokensUsed,
    generationTime: (Date.now() - startTime) / 1000,
    qualityScore,
  }
}

/**
 * Convenience functions for different zoom levels
 */

// Full section generation
export async function generateFullSection(
  context: SectionContext,
  targetWords: number = 1000,
  onProgress?: UnifiedGenerationConfig['onStreamEvent']
): Promise<UnifiedGenerationResult> {
  return generateWithUnifiedTemplate({
    context,
    options: {
      targetWords
    },
    onStreamEvent: onProgress
  })
}

/**
 * Extract a concise summary from generated section content.
 * Takes the first 2 sentences + lists cited paper IDs.
 * No LLM call — pure text extraction.
 */
function extractSectionSummary(title: string, content: string, citations: StructuredCitation[]): string {
  // Extract first 2 sentences as a content preview
  const sentences = content
    .replace(/\[@[^\]]+\]/g, '') // strip [@paperId] citation markers for cleaner summary
    .split(/(?<=[.!?])\s+/)
    .filter(s => s.trim().length > 20)
    .slice(0, 2)
    .join(' ')
    .trim()
  
  const preview = sentences.length > 300 ? sentences.slice(0, 300) + '...' : sentences
  
  // Collect unique cited paper IDs
  const citedPapers = [...new Set(citations.map(c => c.paperId))].slice(0, 8)
  const citedStr = citedPapers.length > 0 
    ? ` (cited: ${citedPapers.join(', ')})` 
    : ''
  
  return `**${title}**: ${preview}${citedStr}`
}

/**
 * Generate a section by producing each subsection separately, then combining.
 * This overcomes the token/verbosity limitation of single-call generation
 * by targeting 600-1400 words per subsection instead of 2000-4000 per section.
 *
 * With the [@paperId] marker approach, no citation renumbering is needed —
 * each subsection's citations are already in their final form.
 */
export async function generateSectionBySubsections(
  parentContext: SectionContext,
  options: BuildPromptOptions,
  onStreamEvent?: (event: StreamEvent) => void
): Promise<UnifiedGenerationResult> {
  const subsections = parentContext.subsections!
  const startTime = Date.now()
  let combinedContent = ''
  const combinedCitations: StructuredCitation[] = []
  let totalTokensUsed = 0
  const subsectionSummaries: string[] = []

  for (let i = 0; i < subsections.length; i++) {
    const sub = subsections[i]

    // Per-subsection word target
    const subTargetWords = sub.expectedWords
      || Math.round((parentContext.expectedWords || 1000) / subsections.length)

    // Leaf context for this subsection — same evidence, scoped key points
    const subContext: SectionContext = {
      sectionKey: `${parentContext.sectionKey}.sub${i}`,
      title: sub.title,
      candidatePaperIds: parentContext.candidatePaperIds,
      contextChunks: parentContext.contextChunks,
      expectedWords: subTargetWords,
      keyPoints: sub.keyPoints,
      // No nested subsections — this is a leaf
    }

    // Build options for this subsection
    const subOptions: BuildPromptOptions = { ...options }
    subOptions.targetWords = subTargetWords
    // Generous 3× multiplier so subsections are never token-starved
    subOptions.maxTokens = Math.max(4000, Math.round(subTargetWords * 3))

    // Inject parent section context so the model knows this is a subsection, not a top-level section
    const parentFraming = `You are writing subsection "${sub.title}" (${i + 1} of ${subsections.length}) inside section "${parentContext.title}". Stay within the subsection scope — do not reintroduce broad context that belongs to the parent section or earlier subsections.`
    const existingSummary = subOptions.previousSectionsSummary || ''
    const parts = [existingSummary, parentFraming]

    // Add previous subsection summaries for within-section coherence
    if (subsectionSummaries.length > 0) {
      parts.push(
        `--- Previous subsections of "${parentContext.title}" ---`,
        ...subsectionSummaries
      )
    }
    subOptions.previousSectionsSummary = parts.filter(Boolean).join('\n')

    const result = await generateWithUnifiedTemplate({
      context: subContext,
      options: subOptions,
      onStreamEvent,
    })

    let subContent = result.content.trim()

    // Convert top-level ## heading to ### for subsection level
    subContent = subContent.replace(/^## /, '### ')

    combinedContent += subContent + '\n\n'
    // No renumbering needed — [@paperId] markers are already in final form
    combinedCitations.push(...result.citations)
    totalTokensUsed += result.tokensUsed

    // Build summary for subsequent subsections
    subsectionSummaries.push(
      extractSectionSummary(sub.title, result.content, result.citations)
    )
  }

  // Prepend parent section heading
  combinedContent = `## ${parentContext.title}\n\n${combinedContent.trim()}`

  const qualityScore = calculateBasicQualityScore({
    content: combinedContent,
    citations: combinedCitations,
    targetWords: parentContext.expectedWords || 1000,
  })

  return {
    content: combinedContent,
    citations: combinedCitations,
    tokensUsed: totalTokensUsed,
    generationTime: (Date.now() - startTime) / 1000,
    qualityScore,
  }
}

/**
 * Batch processing - process multiple sections sequentially with unified approach.
 * Passes rolling summaries of completed sections to each subsequent section
 * for cross-section coherence and overlap avoidance.
 *
 * Sections with subsections are automatically split into per-subsection
 * generation calls for better length compliance.
 * 
 * @param onBatchProgress - Called when a section starts (completed = sections done so far)
 * @param onSectionComplete - Called when a section finishes with its content
 * @param onStreamChunk - Called with each text chunk as it streams (for live preview)
 */
export async function generateMultipleSectionsUnified(
  contexts: SectionContext[],
  options: BuildPromptOptions = {},
  onBatchProgress?: (completed: number, total: number, currentSection: string) => void,
  onSectionComplete?: (sectionTitle: string, content: string, sectionIndex: number, total: number) => void,
  onStreamChunk?: (sectionTitle: string, chunk: string, fullContentSoFar: string) => void
): Promise<UnifiedGenerationResult[]> {
  const results: UnifiedGenerationResult[] = []
  const sectionSummaries: string[] = []
  
  for (let i = 0; i < contexts.length; i++) {
    const sectionTitle = contexts[i].title || contexts[i].sectionKey
    onBatchProgress?.(i, contexts.length, contexts[i].sectionKey)
    
    // Build rolling summary of all previous sections for coherence
    const sectionOptions = { ...options }
    if (sectionSummaries.length > 0) {
      sectionOptions.previousSectionsSummary = sectionSummaries.join('\n')
    }
    
    // Track accumulated content for this section to pass to streaming callback
    let sectionContent = ''
    
    const streamHandler: ((event: StreamEvent) => void) | undefined = onStreamChunk
      ? (event) => {
        if (event.type === 'sentence') {
          sectionContent += event.data.text
          onStreamChunk(sectionTitle, event.data.text, sectionContent)
        }
        }
      : undefined

    // Route: sections WITH subsections → per-subsection generation
    //        sections WITHOUT subsections → single-call generation
    const hasSubsections = contexts[i].subsections && contexts[i].subsections!.length > 0

    let result: UnifiedGenerationResult
    if (hasSubsections) {
      result = await generateSectionBySubsections(
        contexts[i],
        sectionOptions,
        streamHandler
      )
    } else {
      result = await generateWithUnifiedTemplate({
        context: contexts[i],
        options: sectionOptions,
        onStreamEvent: streamHandler,
      })
    }

    results.push(result)
    
    // Build summary from completed section for subsequent sections
    sectionSummaries.push(extractSectionSummary(sectionTitle, result.content, result.citations))
    
    // Notify that section is complete with content
    onSectionComplete?.(sectionTitle, result.content, i + 1, contexts.length)
  }
  
  return results
}
