/**
 * Test Synthesis Pipeline (Paper-Type-Aware)
 * 
 * Comprehensive end-to-end test of the hybrid synthesis system:
 * 1. Extract findings from PDFs
 * 2. Cross-document analysis (patterns, contradictions, gaps)
 * 3. Build paper profile and structural constraints
 * 4. Build synthesis plan with outline alignment
 * 5. Enrich outline sections with synthesis data
 * 
 * Run with: npx tsx scripts/test-synthesis-pipeline.ts
 */

import { config } from 'dotenv'
config({ path: '.env.local' })

import { readFile } from 'fs/promises'
import { existsSync } from 'fs'
import pdfParse from 'pdf-parse'
import { extractPaper } from '../lib/extraction'
import { analyzeFindings, type FindingWithPaper, type AnalysisResult } from '../lib/analysis/cross-document'
import { 
  buildSynthesisPlan, 
  analysisResultToThemeAnalysis,
  type PaperInfo,
  type StructuralConstraints,
  type OutlineSectionInput
} from '../lib/synthesis-engine'
import { buildConstraintsFromProfile, annotateOutlineSections } from '../lib/synthesis-engine/constraint-builder'
import type { PaperProfile, SectionProfile } from '../lib/generation/paper-profile-types'
import type { PaperTypeKey } from '../types/simplified'

// =============================================================================
// Test Configuration
// =============================================================================

interface TestPaper {
  name: string
  path: string
}

const TEST_PAPERS: TestPaper[] = [
  {
    name: 'Tomato Spoilage Study',
    path: './AJPB+2022+4+2+no+4+Garba+Tomato+28+31+-+Copy.pdf'
  },
  {
    name: 'Greenland Identity Politics',
    path: './lbaulund,+What+kind+of+nation+state+will+Greenland+be_+Securitization+theory+as+a+strategy+for+analyzing+identity+politics++.pdf'
  }
]

// =============================================================================
// Mock Data Factories
// =============================================================================

/**
 * Create a mock PaperProfile for testing
 * In production, this is generated by generatePaperProfile()
 */
function createMockPaperProfile(
  topic: string,
  paperType: PaperTypeKey = 'literatureReview'
): PaperProfile {
  const currentYear = new Date().getFullYear()
  
  // Section profiles based on paper type
  const appropriateSections: SectionProfile[] = paperType === 'literatureReview' 
    ? [
        {
          key: 'introduction',
          title: 'Introduction',
          purpose: 'Establish context, define scope, and state the research question',
          minWords: 300,
          maxWords: 600,
          citationExpectation: 'moderate',
          keyElements: ['research question', 'scope', 'significance']
        },
        {
          key: 'literatureReview',
          title: 'Literature Review Overview',
          purpose: 'Provide overview of the literature landscape',
          minWords: 400,
          maxWords: 800,
          citationExpectation: 'heavy',
          keyElements: ['key themes', 'major works', 'evolution of field']
        },
        {
          key: 'thematicAnalysis',
          title: 'Thematic Analysis',
          purpose: 'Analyze literature by themes, synthesizing across sources',
          minWords: 800,
          maxWords: 1500,
          citationExpectation: 'heavy',
          keyElements: ['theme synthesis', 'cross-study patterns', 'evidence integration']
        },
        {
          key: 'discussion',
          title: 'Discussion',
          purpose: 'Discuss implications, contradictions, and gaps',
          minWords: 400,
          maxWords: 700,
          citationExpectation: 'moderate',
          keyElements: ['implications', 'contradictions', 'limitations']
        },
        {
          key: 'conclusion',
          title: 'Conclusion',
          purpose: 'Summarize findings and suggest future directions',
          minWords: 200,
          maxWords: 400,
          citationExpectation: 'light',
          keyElements: ['summary', 'future directions', 'significance']
        }
      ]
    : [
        {
          key: 'introduction',
          title: 'Introduction',
          purpose: 'Introduce the research problem and objectives',
          minWords: 300,
          maxWords: 500,
          citationExpectation: 'moderate',
          keyElements: ['problem statement', 'objectives', 'significance']
        },
        {
          key: 'literatureReview',
          title: 'Literature Review',
          purpose: 'Review relevant prior work',
          minWords: 500,
          maxWords: 1000,
          citationExpectation: 'heavy',
          keyElements: ['prior work', 'theoretical framework', 'gaps']
        },
        {
          key: 'methodology',
          title: 'Methodology',
          purpose: 'Describe research methods',
          minWords: 400,
          maxWords: 800,
          citationExpectation: 'light',
          keyElements: ['methods', 'data collection', 'analysis approach']
        },
        {
          key: 'results',
          title: 'Results',
          purpose: 'Present findings',
          minWords: 400,
          maxWords: 800,
          citationExpectation: 'none',
          keyElements: ['findings', 'data', 'observations']
        },
        {
          key: 'discussion',
          title: 'Discussion',
          purpose: 'Interpret results and compare with prior work',
          minWords: 400,
          maxWords: 700,
          citationExpectation: 'moderate',
          keyElements: ['interpretation', 'comparison', 'implications']
        },
        {
          key: 'conclusion',
          title: 'Conclusion',
          purpose: 'Summarize and conclude',
          minWords: 200,
          maxWords: 400,
          citationExpectation: 'light',
          keyElements: ['summary', 'contributions', 'future work']
        }
      ]

  return {
    generatedAt: new Date().toISOString(),
    topic,
    paperType,
    hasOriginalResearch: paperType !== 'literatureReview',
    discipline: {
      primary: 'Interdisciplinary Research',
      related: ['Social Sciences', 'Natural Sciences'],
      methodologicalTraditions: ['systematic review', 'thematic analysis'],
      fieldCharacteristics: {
        paceOfChange: 'moderate',
        theoryVsEmpirical: 'balanced',
        practitionerRelevance: 'medium'
      }
    },
    structure: {
      appropriateSections,
      inappropriateSections: [
        { name: 'Experimental Setup', reason: 'Not applicable for literature review' }
      ],
      requiredElements: ['research question', 'synthesis', 'conclusions']
    },
    sourceExpectations: {
      minimumUniqueSources: 5,
      idealSourceCount: 15,
      sourceTypeDistribution: [
        { type: 'peer-reviewed journals', percentage: 70, importance: 'required' },
        { type: 'conference papers', percentage: 20, importance: 'recommended' },
        { type: 'books/chapters', percentage: 10, importance: 'optional' }
      ],
      recencyProfile: 'balanced',
      searchYearRange: {
        fromYear: currentYear - 10,
        toYear: currentYear,
        rationale: 'Balanced coverage of recent and foundational literature'
      },
      recencyGuidance: 'Include both recent advances and foundational works'
    },
    qualityCriteria: [
      {
        criterion: 'Synthesis Quality',
        description: 'Sources should be synthesized, not just summarized',
        howToAchieve: 'Compare and contrast findings across multiple sources'
      },
      {
        criterion: 'Critical Analysis',
        description: 'Demonstrate critical engagement with the literature',
        howToAchieve: 'Identify strengths, weaknesses, and gaps in existing research'
      }
    ],
    coverage: {
      requiredThemes: ['main topic overview', 'key findings', 'methodological approaches'],
      recommendedThemes: ['historical development', 'future directions'],
      debates: ['methodological disagreements', 'theoretical tensions'],
      methodologicalConsiderations: ['selection criteria', 'scope boundaries'],
      commonPitfalls: ['excessive summarization', 'lack of synthesis', 'missing critical analysis']
    },
    genreRules: [
      {
        rule: 'Organize by theme, not by source',
        rationale: 'Thematic organization demonstrates synthesis ability'
      },
      {
        rule: 'Connect sources through comparative analysis',
        rationale: 'Shows understanding of how sources relate to each other'
      }
    ]
  }
}

/**
 * Create outline sections from profile for plan alignment
 */
function createOutlineSectionsFromProfile(
  profile: PaperProfile,
  paperType: PaperTypeKey,
  targetWordCount: number
): OutlineSectionInput[] {
  const sections = profile.structure.appropriateSections
  const totalMinWords = sections.reduce((sum, s) => sum + s.minWords, 0)
  
  return annotateOutlineSections(
    sections.map(section => ({
      sectionKey: section.key,
      title: section.title,
      expectedWords: Math.round((section.minWords / totalMinWords) * targetWordCount),
      keyPoints: section.keyElements
    })),
    paperType
  )
}

// =============================================================================
// Extraction
// =============================================================================

interface ExtractedPaper {
  id: string
  title: string
  authors: string[]
  year?: number
  domain: string
  findings: FindingWithPaper[]
}

async function extractPaperData(paper: TestPaper): Promise<ExtractedPaper | null> {
  console.log(`\n📄 Extracting: ${paper.name}`)
  
  if (!existsSync(paper.path)) {
    console.log(`   ⚠️  File not found: ${paper.path}`)
    return null
  }
  
  try {
    const pdfBuffer = await readFile(paper.path)
    const pdfData = await pdfParse(pdfBuffer)
    
    const paperId = `paper-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
    
    const result = await extractPaper({
      paperId,
      text: pdfData.text
    })
    
    if (!result.success || !result.extraction) {
      console.log(`   ❌ Extraction failed: ${result.error}`)
      return null
    }
    
    const ext = result.extraction
    console.log(`   ✅ Extracted ${ext.findings.length} findings`)
    console.log(`   Title: "${ext.metadata.title}"`)
    
    const findings: FindingWithPaper[] = ext.findings.map(f => ({
      ...f,
      paperId: ext.paperId,
      paperTitle: ext.metadata.title,
      paperYear: ext.metadata.year,
      paperDomain: ext.metadata.domain
    }))
    
    return {
      id: ext.paperId,
      title: ext.metadata.title,
      authors: ext.metadata.authors,
      year: ext.metadata.year,
      domain: ext.metadata.domain,
      findings
    }
  } catch (error) {
    console.log(`   ❌ Error: ${error instanceof Error ? error.message : 'Unknown error'}`)
    return null
  }
}

// =============================================================================
// Display Helpers
// =============================================================================

function displayAnalysisResults(analysis: AnalysisResult): void {
  console.log('\n📊 ANALYSIS RESULTS')
  console.log('─'.repeat(60))
  
  // Patterns
  console.log(`\n🔍 Patterns (${analysis.patterns.length}):`)
  analysis.patterns.forEach((p, i) => {
    console.log(`\n   ${i + 1}. ${p.claim}`)
    console.log(`      Support: ${p.support.count}/${p.support.total} papers (${Math.round(p.support.count / p.support.total * 100)}%)`)
    console.log(`      Confidence: ${(p.confidence * 100).toFixed(0)}%`)
    console.log(`      Consistency: ${p.consistency}`)
  })
  
  // Contradictions
  console.log(`\n⚡ Contradictions (${analysis.contradictions.length}):`)
  analysis.contradictions.forEach((c, i) => {
    console.log(`\n   ${i + 1}. ${c.description}`)
    c.sides.forEach((side, j) => {
      console.log(`      Side ${j + 1}: ${side.position} (${side.papers.length} papers)`)
    })
    if (c.possibleExplanation) {
      console.log(`      Possible explanation: ${c.possibleExplanation}`)
    }
  })
  
  // Gaps
  console.log(`\n🕳️  Gaps (${analysis.gaps.length}):`)
  analysis.gaps.forEach((g, i) => {
    console.log(`\n   ${i + 1}. ${g.description}`)
    console.log(`      Type: ${g.type}`)
    console.log(`      Relevance: ${g.relevance}`)
    console.log(`      Confidence: ${(g.confidence * 100).toFixed(0)}%`)
  })
  
  // Key Insights
  if (analysis.keyInsights.length > 0) {
    console.log(`\n💡 Key Insights:`)
    analysis.keyInsights.forEach((insight, i) => {
      console.log(`   ${i + 1}. ${insight}`)
    })
  }
}

function displayConstraints(constraints: StructuralConstraints): void {
  console.log('\n📐 STRUCTURAL CONSTRAINTS')
  console.log('─'.repeat(60))
  console.log(`Paper Type: ${constraints.paperType}`)
  console.log(`Discipline: ${constraints.disciplineContext}`)
  console.log(`Section Limits: ${constraints.minSections}-${constraints.maxSections}`)
  console.log(`Source Requirements: ${constraints.minSources} min, ${constraints.idealSources} ideal`)
  
  console.log(`\nRequired Sections (${constraints.requiredSections.length}):`)
  constraints.requiredSections.forEach((s, i) => {
    const litFlag = s.isLiteratureFocused ? '📚' : '🔬'
    console.log(`   ${i + 1}. ${litFlag} ${s.name} (${s.key})`)
    if (s.minWords && s.maxWords) {
      console.log(`      Words: ${s.minWords}-${s.maxWords}`)
    }
    if (s.purpose) {
      console.log(`      Purpose: ${s.purpose}`)
    }
  })
  
  if (constraints.forbiddenSections.length > 0) {
    console.log(`\nForbidden Sections: ${constraints.forbiddenSections.join(', ')}`)
  }
}

function displayPlan(plan: NonNullable<Awaited<ReturnType<typeof buildSynthesisPlan>>['plan']>): void {
  console.log('\n📋 SYNTHESIS PLAN')
  console.log('─'.repeat(60))
  console.log(`Title: "${plan.overview.title}"`)
  console.log(`\nAbstract:\n${plan.overview.abstract}`)
  console.log(`\nNarrative Strategy: ${plan.overview.narrativeStrategy}`)
  console.log(`Total Sections: ${plan.overview.totalSections}`)
  console.log(`Target Word Count: ${plan.overview.totalWordCount}`)
  
  console.log('\n─'.repeat(40))
  console.log('GLOBAL GUIDANCE')
  console.log('─'.repeat(40))
  console.log(`Audience: ${plan.globalGuidance.audienceLevel}`)
  console.log(`Writing Style: ${plan.globalGuidance.writingStyle}`)
  console.log(`Citation Approach: ${plan.globalGuidance.citationApproach}`)
  console.log(`Key Themes: ${plan.globalGuidance.keyThemes.join(', ')}`)
  
  console.log('\n─'.repeat(40))
  console.log('SECTIONS')
  console.log('─'.repeat(40))
  
  plan.sections.forEach((section, i) => {
    const litFlag = section.isLiteratureFocused ? '📚' : '🔬'
    console.log(`\n${i + 1}. ${litFlag} ${section.title}`)
    console.log(`   Outline Key: ${section.outlineSectionKey}`)
    console.log(`   Purpose: ${section.purpose}`)
    console.log(`   Target Words: ${section.targetWordCount}`)
    console.log(`   Approach: ${section.writingGuidance.approach}`)
    console.log(`   Tone: ${section.writingGuidance.tone}`)
    
    if (section.content.patterns.length > 0) {
      console.log(`   Patterns (${section.content.patterns.length}):`)
      section.content.patterns.forEach((p, j) => {
        console.log(`      ${j + 1}. ${p.claim.slice(0, 60)}...`)
        console.log(`         → ${p.data.supportStatement}`)
      })
    }
    
    if (section.content.contradictions.length > 0) {
      console.log(`   Contradictions (${section.content.contradictions.length}):`)
      section.content.contradictions.forEach((c, j) => {
        console.log(`      ${j + 1}. ${c.description.slice(0, 60)}...`)
      })
    }
    
    if (section.content.gaps.length > 0) {
      console.log(`   Gaps (${section.content.gaps.length}):`)
      section.content.gaps.forEach((g, j) => {
        console.log(`      ${j + 1}. ${g.description.slice(0, 60)}...`)
      })
    }
    
    console.log(`   Key Points:`)
    section.keyPointsToMake.forEach((point, j) => {
      console.log(`      ${j + 1}. ${point}`)
    })
  })
}

// =============================================================================
// Main Test Function
// =============================================================================

async function main() {
  console.log('╔══════════════════════════════════════════════════════════════════════════════╗')
  console.log('║              SYNTHESIS PIPELINE TEST (Paper-Type-Aware)                       ║')
  console.log('║    Extraction → Analysis → Profile → Constraints → Plan → Enrichment         ║')
  console.log('╚══════════════════════════════════════════════════════════════════════════════╝')
  
  const totalStartTime = Date.now()
  const timings: Record<string, number> = {}
  
  // =========================================================================
  // STEP 1: EXTRACT FINDINGS FROM PAPERS
  // =========================================================================
  console.log('\n' + '='.repeat(80))
  console.log('STEP 1: EXTRACT FINDINGS FROM PAPERS')
  console.log('='.repeat(80))
  
  const stepStart = Date.now()
  const extractedPapers: ExtractedPaper[] = []
  const allFindings: FindingWithPaper[] = []
  
  for (const paper of TEST_PAPERS) {
    const extracted = await extractPaperData(paper)
    if (extracted) {
      extractedPapers.push(extracted)
      allFindings.push(...extracted.findings)
    }
  }
  
  timings['extraction'] = Date.now() - stepStart
  
  console.log(`\n📊 Extraction Summary:`)
  console.log(`   Papers processed: ${TEST_PAPERS.length}`)
  console.log(`   Papers extracted: ${extractedPapers.length}`)
  console.log(`   Total findings: ${allFindings.length}`)
  console.log(`   Time: ${timings['extraction']}ms`)
  
  if (allFindings.length === 0) {
    console.log('\n❌ No findings extracted. Cannot proceed.')
    console.log('   Make sure the test PDF files exist in the project root.')
    return
  }
  
  // =========================================================================
  // STEP 2: CROSS-DOCUMENT ANALYSIS
  // =========================================================================
  console.log('\n' + '='.repeat(80))
  console.log('STEP 2: CROSS-DOCUMENT ANALYSIS')
  console.log('='.repeat(80))
  
  const analysisStart = Date.now()
  const analysis = await analyzeFindings({
    projectId: 'test-project',
    findings: allFindings
  })
  timings['analysis'] = Date.now() - analysisStart
  
  displayAnalysisResults(analysis)
  console.log(`\n⏱️  Analysis Time: ${timings['analysis']}ms`)
  
  // =========================================================================
  // STEP 3: TEST THEME ADAPTER (Pipeline Compatibility)
  // =========================================================================
  console.log('\n' + '='.repeat(80))
  console.log('STEP 3: THEME ADAPTER (Pipeline Compatibility)')
  console.log('='.repeat(80))
  
  const papers: PaperInfo[] = extractedPapers.map(p => ({
    id: p.id,
    title: p.title,
    authors: p.authors,
    year: p.year,
    domain: p.domain
  }))
  
  const themeAnalysis = analysisResultToThemeAnalysis(analysis, papers)
  
  console.log(`\n📋 ThemeAnalysis (for pipeline compatibility):`)
  console.log(`   Emergent Themes: ${themeAnalysis.emergentThemes.length}`)
  console.log(`   Scholarly Debates: ${themeAnalysis.debates.length}`)
  console.log(`   Literature Gaps: ${themeAnalysis.gaps.length}`)
  console.log(`   Pivotal Papers: ${themeAnalysis.pivotalPapers.length}`)
  console.log(`   Organization: ${themeAnalysis.organizationSuggestion.approach}`)
  console.log(`   Confidence: ${(themeAnalysis.confidence * 100).toFixed(0)}%`)
  
  // =========================================================================
  // STEP 4: CREATE PAPER PROFILE & STRUCTURAL CONSTRAINTS
  // =========================================================================
  console.log('\n' + '='.repeat(80))
  console.log('STEP 4: PAPER PROFILE & STRUCTURAL CONSTRAINTS')
  console.log('='.repeat(80))
  
  const paperType: PaperTypeKey = 'literatureReview'
  const topic = 'Cross-disciplinary research synthesis'
  
  console.log(`\n📝 Creating mock profile for:`)
  console.log(`   Topic: "${topic}"`)
  console.log(`   Paper Type: ${paperType}`)
  
  const profile = createMockPaperProfile(topic, paperType)
  const constraints = buildConstraintsFromProfile(profile)
  
  displayConstraints(constraints)
  
  // =========================================================================
  // STEP 5: CREATE OUTLINE SECTIONS
  // =========================================================================
  console.log('\n' + '='.repeat(80))
  console.log('STEP 5: CREATE OUTLINE SECTIONS')
  console.log('='.repeat(80))
  
  const targetWordCount = 2500
  const outlineSections = createOutlineSectionsFromProfile(profile, paperType, targetWordCount)
  
  console.log(`\n📑 Outline Sections (${outlineSections.length}):`)
  outlineSections.forEach((section, i) => {
    const litFlag = section.isLiteratureFocused ? '📚 Literature-focused' : '🔬 Empirical'
    console.log(`   ${i + 1}. ${section.title} (${section.sectionKey})`)
    console.log(`      ${litFlag}`)
    console.log(`      Expected words: ${section.expectedWords}`)
    if (section.keyPoints && section.keyPoints.length > 0) {
      console.log(`      Key points: ${section.keyPoints.join(', ')}`)
    }
  })
  
  // =========================================================================
  // STEP 6: BUILD SYNTHESIS PLAN (with new required fields)
  // =========================================================================
  console.log('\n' + '='.repeat(80))
  console.log('STEP 6: BUILD SYNTHESIS PLAN')
  console.log('='.repeat(80))
  
  const planStart = Date.now()
  const planResult = await buildSynthesisPlan({
    projectId: 'test-project',
    analysis,
    papers,
    // NEW: Required fields for paper-type-aware planning
    paperType,
    paperProfile: profile,
    structuralConstraints: constraints,
    outlineSections,
    // Optional
    targetWordCount,
    audienceLevel: 'academic'
  })
  timings['planning'] = Date.now() - planStart
  
  if (!planResult.success || !planResult.plan) {
    console.log(`\n❌ Plan generation failed: ${planResult.error}`)
    return
  }
  
  displayPlan(planResult.plan)
  console.log(`\n⏱️  Planning Time: ${timings['planning']}ms`)
  
  // =========================================================================
  // STEP 7: SUMMARY & NEXT STEPS
  // =========================================================================
  console.log('\n' + '='.repeat(80))
  console.log('SUMMARY')
  console.log('='.repeat(80))
  
  const totalTime = Date.now() - totalStartTime
  
  console.log(`
📊 PIPELINE STATISTICS
─────────────────────────────────────────────
Papers Processed:     ${extractedPapers.length}
Findings Extracted:   ${allFindings.length}
Patterns Found:       ${analysis.patterns.length}
Contradictions Found: ${analysis.contradictions.length}
Gaps Found:           ${analysis.gaps.length}
Plan Sections:        ${planResult.plan.sections.length}
─────────────────────────────────────────────

⏱️  TIMING BREAKDOWN
─────────────────────────────────────────────
Extraction:    ${timings['extraction']}ms
Analysis:      ${timings['analysis']}ms
Planning:      ${timings['planning']}ms
─────────────────────────────────────────────
Total:         ${totalTime}ms (${(totalTime / 1000).toFixed(1)}s)

🔮 NEXT STEPS (in production pipeline)
─────────────────────────────────────────────
The plan is now ready to be used with:
1. enrichOutlineSections() - Add synthesis patterns to outline
2. generateMultipleSectionsUnified() - Generate actual content

The synthesis plan ensures:
✓ Paper-type-appropriate sections
✓ Literature-focused sections get synthesis enrichment
✓ Empirical sections (Methods/Results) don't get patterns
✓ Pre-computed statistics ready for insertion
✓ Writing guidance for each section
`)
  
  console.log('='.repeat(80))
  console.log('✅ SYNTHESIS PIPELINE TEST COMPLETE!')
  console.log('='.repeat(80))
}

main().catch(console.error)
