import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for GenPaper - AI-powered research paper generation platform.',
}

export default function TermsOfServicePage() {
  const lastUpdated = 'February 7, 2025'
  const companyName = 'GenPaper'
  const contactEmail = process.env.CONTACT_EMAIL || 'support@genpaper.app'
  
  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-4xl mx-auto px-4 py-16">
        <h1 className="font-instrument text-4xl tracking-tight mb-4">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: {lastUpdated}</p>
        
        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8">
          
          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using {companyName} (&quot;the Service&quot;), you agree to be bound by these 
              Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you may not use the Service.
            </p>
            <p>
              We reserve the right to update these Terms at any time. Continued use of the Service after 
              changes constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">2. Description of Service</h2>
            <p>
              {companyName} is an AI-powered platform that assists users in generating, editing, and 
              formatting academic research papers. The Service includes:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>AI-assisted paper generation and writing</li>
              <li>Literature search and citation management</li>
              <li>Document editing and formatting tools</li>
              <li>Export functionality for various formats</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">3. User Accounts</h2>
            <p>
              To use certain features of the Service, you must create an account. You are responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Providing accurate and complete registration information</li>
              <li>Notifying us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">4. Acceptable Use</h2>
            <p>You agree NOT to use the Service to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Submit AI-generated content as your own original work without proper disclosure, where required by your institution</li>
              <li>Violate any academic integrity policies of your educational institution</li>
              <li>Generate content that is illegal, harmful, threatening, abusive, or defamatory</li>
              <li>Infringe on intellectual property rights of others</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Use automated systems to access the Service without permission</li>
              <li>Resell or redistribute the Service without authorization</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">5. AI-Generated Content Disclaimer</h2>
            <p className="font-semibold text-amber-600 dark:text-amber-400">
              IMPORTANT: Content generated by {companyName} is created with AI assistance.
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Academic Integrity:</strong> You are responsible for ensuring that your use of 
                AI-generated content complies with your institution&apos;s academic integrity policies. 
                Many institutions require disclosure of AI assistance.
              </li>
              <li>
                <strong>Accuracy:</strong> While we strive for accuracy, AI-generated content may contain 
                errors, inaccuracies, or hallucinations. You must review and verify all content before submission.
              </li>
              <li>
                <strong>Citations:</strong> Although we attempt to provide accurate citations, you are 
                responsible for verifying all references and ensuring they exist and are correctly attributed.
              </li>
              <li>
                <strong>Not a Substitute:</strong> The Service is a writing assistant, not a replacement 
                for your own research, critical thinking, and scholarly work.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">6. Intellectual Property</h2>
            <p>
              <strong>Your Content:</strong> You retain ownership of content you create using the Service. 
              By using the Service, you grant us a limited license to process your content solely to 
              provide the Service.
            </p>
            <p>
              <strong>Our Service:</strong> The Service, including its software, design, and documentation, 
              is owned by {companyName} and protected by intellectual property laws. You may not copy, 
              modify, or reverse engineer any part of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">7. Payment Terms</h2>
            <p>
              Certain features require a paid subscription. By subscribing, you agree to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Pay all applicable fees at the prices in effect when charges are incurred</li>
              <li>Automatic renewal of subscriptions unless cancelled before the renewal date</li>
              <li>No refunds for partial billing periods, except as required by law</li>
            </ul>
            <p>
              We reserve the right to change pricing with 30 days&apos; notice. Continued use after a 
              price change constitutes acceptance of the new pricing.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">8. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                The Service is provided &quot;AS IS&quot; without warranties of any kind, express or implied.
              </li>
              <li>
                We are not liable for any indirect, incidental, special, consequential, or punitive damages.
              </li>
              <li>
                Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.
              </li>
              <li>
                We are not responsible for any academic consequences resulting from your use of the Service, 
                including but not limited to academic misconduct findings.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">9. Termination</h2>
            <p>
              We may terminate or suspend your account at any time for violation of these Terms or for 
              any other reason at our discretion. Upon termination:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Your right to use the Service immediately ceases</li>
              <li>We may delete your account and associated data</li>
              <li>Provisions that by their nature should survive will remain in effect</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">10. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the 
              jurisdiction in which {companyName} is incorporated, without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">11. Contact Information</h2>
            <p>
              For questions about these Terms, please contact us at:{' '}
              <a href={`mailto:${contactEmail}`} className="text-primary hover:underline">
                {contactEmail}
              </a>
            </p>
          </section>

        </div>
      </div>
    </div>
  )
}
